apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: {{ .Values.namespace.name }}
  labels:
    k8s-app: fluent-bit
data:
  fluent-bit.conf: |
    [SERVICE]
      Flush                     5
      Log_Level                 info
      Daemon                    off
      Parsers_File              parsers.conf
      HTTP_Server               "On"
      HTTP_Listen               0.0.0.0
      HTTP_Port                 2020
        
    @INCLUDE input-kubernetes.conf

  input-kubernetes.conf: |
    [INPUT]
      Name              tail
      Tag               kube.*
      Path              /var/log/containers/*.log
      Parser            docker
      DB                /var/log/flb_kube.db
      Mem_Buf_Limit     5MB
      Skip_Long_Lines   On
      Refresh_Interval  10
    [FILTER]
      Name                kubernetes
      Match               kube.*
      Kube_URL            https://kubernetes.default.svc.cluster.local:443
      Merge_Log           On
      K8S-Logging.Parser  On
      Merge_Log_Key       log_processed
      K8S-Logging.Exclude On
    [OUTPUT]
      Name  opensearch
      Match *
      Host  {{ .Values.data.host }}
      Port  443
      AWS_Auth On
      AWS_Region {{ .Values.data.region }}
      Replace_Dots On
      tls     On
      Index fluent-bit
      Retry_Limit 6
  parsers.conf: |
    [PARSER]
      Name                docker
      Format              json
      Time_Key            time
      Time_Format         %Y-%m-%dT%H:%M:%S.%LZ
    [PARSER]
      Name                syslog
      Format              regex
      Regex               ^(?<time>[^ ]* {1,2}[^ ]* [^ ]*) (?<host>[^ ]*) (?<ident>[a-zA-Z0-9_\/\.\-]*)(?:\[(?<pid>[0-9]+)\])?(?:[^\:]*\:)? *(?<message>.*)$
      Time_Key            time
      Time_Format         %b %d %H:%M:%S
    [PARSER]
      Name                container_firstline
      Format              regex
      Regex               (?<log>(?<="log":")\S(?!\.).*?)(?<!\\)".*(?<stream>(?<="stream":").*?)".*(?<time>\d{4}-\d{1,2}-\d{1,2}T\d{2}:\d{2}:\d{2}\.\w*).*(?=})
      Time_Key            time
      Time_Format         %Y-%m-%dT%H:%M:%S.%LZ
    [PARSER]
      Name                cwagent_firstline
      Format              regex
      Regex               (?<log>(?<="log":")\d{4}[\/-]\d{1,2}[\/-]\d{1,2}[ T]\d{2}:\d{2}:\d{2}(?!\.).*?)(?<!\\)".*(?<stream>(?<="stream":").*?)".*(?<time>\d{4}-\d{1,2}-\d{1,2}T\d{2}:\d{2}:\d{2}\.\w*).*(?=})
      Time_Key            time
      Time_Format         %Y-%m-%dT%H:%M:%S.%LZ