apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace.name }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccountsRoles.fluent_bit_arn }}