---
  - name: Build and push to ECR
    hosts: all
    vars_files:
      - external_vars.yml
    tasks:
      - name: Login into ECR
        shell: |
          aws ecr-public get-login-password --region "{{ region }}" | docker login --username AWS --password-stdin "{{ repo }}"
      - name: Build an image and push it to a repo
        docker_image:
          build:
            path: ../app
          name: "{{ image }}"
          tag: "{{ tag }}"
          source: build
      - name: Add tag latest to image
        docker_image:
          name: "{{ image }}"
          repository: "{{ repo }}/{{ image }}:{{ tag }}"
          force_tag: true
          source: local
      - name: Push latest to repo
        docker_image:
          name: "{{ repo }}/{{ image }}:{{ tag }}"
          push: true
          source: local
