---
  - name: Deploy app
    hosts: all
      - name: Update kubeconfig
        shell: |
          aws eks update-kubeconfig --region us-east-1 --name testtask-cluster
      - name: Set image
        shell: |
          kubectl set image deployment/testtask-deployment testask=public.ecr.aws/a5a9t4e9/testtask:latest