---
  - name: Deploy app
    hosts: all
    vars_files:
      - external_vars.yml
    tasks:
      - name: Update kubeconfig
        shell: |
          aws eks update-kubeconfig --region "{{ region }}" --name "{{ cluster }}"
      - name: Set image
        shell: |
          kubectl set image deployment/testtask-deployment testtask="{{ repo }}/{{ image }}:{{ tag }}"