apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistentVolumeClaim }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.storageClass.metadata.name }}
  resources:
    requests:
      storage: 5Gi