apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.metadata.name }}
data:
  node_env: {{ .Values.data.NODE_ENV | quote }}
  contenful_delivery_api_host: {{ .Values.data.CONTENTFUL_DELIVERY_API_HOST | quote }}
  contenful_preview_api_host: {{ .Values.data.CONTENTFUL_PREVIEW_API_HOST | quote }}
  port: {{ .Values.data.PORT | quote }}