apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secrets-provider
spec:
  provider: aws
  secretObjects:
    - secretName: {{ .Values.secretObjects.secretName}}
      type: Opaque
      data:
        - objectName: "CONTENTFUL_SPACE_ID"
          key: CONTENTFUL_SPACE_ID
        - objectName: "CONTENTFUL_DELIVERY_TOKEN"
          key: CONTENTFUL_DELIVERY_TOKEN
        - objectName: "CONTENTFUL_PREVIEW_TOKEN"
          key: CONTENTFUL_PREVIEW_TOKEN
  parameters:
    region: {{ .Values.parameters.region }}
    objects: |
      - objectName: {{ .Values.parameters.objectName }}
        jmesPath:
            - path: "CONTENTFUL_SPACE_ID"
              objectAlias: "CONTENTFUL_SPACE_ID"
            - path: "CONTENTFUL_DELIVERY_TOKEN"
              objectAlias: "CONTENTFUL_DELIVERY_TOKEN"
            - path: "CONTENTFUL_PREVIEW_TOKEN"
              objectAlias: "CONTENTFUL_PREVIEW_TOKEN"