apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name}}
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccountsRoles.secretManagerArn }}