apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.metadata.name}}
spec:
  ports:
  - port: {{ .Values.service.port}}
    targetPort: {{ .Values.container.port}}
    protocol: TCP
  type: {{ .Values.service.type}}
  selector:
    app: {{ .Values.deployment.pod}}